# Generated by Django 5.1.7 on 2025-06-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente_id',
        ),
    ]
