# Generated by Django 5.1.7 on 2025-06-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_carrito_carritoproducto_carrito_productos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='link_pago',
            field=models.URLField(blank=True, null=True),
        ),
    ]
